name: Bug report
description: Report a defect or regression
title: "[bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What broke?
      placeholder: Short defect summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps and inputs
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Expected result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Actual result
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Environment and context
      description: Runtime, OS, branch, logs, screenshots
      placeholder: Add details here
