name: Feature request
description: Propose a new capability or improvement
title: "[feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What fails today?
      placeholder: Clear user or business pain
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Desired outcome
      description: What should happen instead?
      placeholder: Clear expected behavior
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Reliability, cost, speed, productivity (optional)
      placeholder: Expected outcomes
